name: build

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  test:
    runs-on: ubuntu-latest
    name: build
    steps:
      - uses: actions/checkout@v3
      - name: Install mamba
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: environment.yml
          environment-name: muscle-driven-bicycle-paper
          init-shell: bash
      - name: Install LaTeX
        run: sudo apt-get install -y texlive
      - name: Build paper
        run: |
          micromamba info
          micromamba list
          make
          make paper.html
          mkdir output/
          mv paper.pdf output/
          mv paper.html output/index.html
      - name: Deploy the website
        if: ${{ github.event_name == 'push' }}
        run: |
          git config --global user.name "Github Actions"
          git config --global user.email brocksam@users.noreply.github.com
          git remote add deploy "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/brocksam/muscle-driven-bicycle-paper.git"
          ghp-import --no-jekyll --no-history -r deploy -m "Update deployment via Github Actions [skip ci]" -p output
